<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class FormFields extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\FormField::factory()->createManyQuietly([
            ['form_id' => 1, 'name' => 'prioritise_for_productivity', 'element' => 'radio', 'label' => 'Prioritise for productivity', 'hint' => 'I effectively prioritise tasks by maximising resources, including time management and digital tools, to optimise efficiency and productivity within set timeframes for myself and my areas of responsibility. How do you rate yourself against this competency?', 'placeholder' => null, 'required' => 1],
            ['form_id' => 1, 'name' => 'keep_safe_and_develop', 'element' => 'radio', 'label' => 'Keep safe and developing wellbeing strategies', 'hint' => 'I take responsibility for managing and maintaining my energy levels and wellbeing, including my emotional, mental, and physical health, recognising its impact on my ability to perform, and ensuring I access available support when needed.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 1, 'name' => 'continuous_development', 'element' => 'radio', 'label' => 'Commit to continuing professional development', 'hint' => 'I commit to continuing professional development, building my own skills and knowledge through learning, including seeking feedback and using reflective and reflexive practice to enhance my management and leadership skills.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 1, 'name' => 'balancing_safety_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Balancing safety, productivity and wellbeing', 'placeholder' => null, 'required' => 0],

            ['form_id' => 2, 'name' => 'communicate_with_clarity', 'element' => 'radio', 'label' => 'Communicate with clarity and purpose', 'hint' => 'I communicate clearly, concisely, and respectfully to avoid misunderstandings and ensure effective information sharing.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 2, 'name' => 'encourage_open_dialogue', 'element' => 'radio', 'label' => 'Encourage open dialogue and feedback', 'hint' => 'I encourage open dialogue and feedback, to foster a supportive environment, by ensuring colleagues and patients feel safe to speak up, and consciously listening to others, sharing concerns and challenge upwards.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 2, 'name' => 'influence', 'element' => 'radio', 'label' => 'Influence, negotiate and manage upwards', 'hint' => 'I recognise the value of influencing others, including using storytelling, expertise and lived experiences and knowing how to manage upwards, to effectively gain support and achieve desired outcomes.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 2, 'name' => 'Communicating_and_listening_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Communicating and listening effectively"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 3, 'name' => 'take_accountability', 'element' => 'radio', 'label' => 'Take accountability for my actions', 'hint' => 'I reflect on my actions, reactions and biases, both conscious and unconscious, to better understand and manage their impact on myself and others.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 3, 'name' => 'be_visible', 'element' => 'radio', 'label' => 'Be visible, transparent and present', 'hint' => 'I develop trust and engagement with others, ensuring that I am approachable, value their input, share information openly, and encourage honest feedback to foster a collaborative and transparent environment.', 'placeholder' => null, 'required' => 1],
            ['form_id' => 3, 'name' => 'manage_with_civility', 'element' => 'radio', 'label' => 'Manage with civility and compassion', 'hint' => 'I role model respectful behaviour, consciously demonstrating what civility and compassion mean within the healthcare workplace and creating a positive and supportive atmosphere.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 3, 'name' => 'delivering_with_accountability_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Delivering with integrity and accountability"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 4, 'name' => 'sense_of_engagement', 'element' => 'radio', 'label' => 'Create a sense of engagement', 'hint' => 'I foster engagement by clarifying roles, valuing contributions, supporting development, and celebrating successes, including learning from challenges.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 4, 'name' => 'support_people', 'element' => 'radio', 'label' => 'Support people to feel safe in the workplace', 'hint' => 'I identify and remove hazards which could cause harm to myself or others, by dynamically assessing if it is safe to act, considering both physical and psychological safety, and reporting issues, concerns and incidents, including near-misses, promptly.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 4, 'name' => 'managing_challenging_circumstances', 'element' => 'radio', 'label' => 'Managing challenging circumstances', 'hint' => 'I approach challenging circumstances calmly, by actively listening to ensure understanding, and seeking help or advice if required, to promptly address difficult situation', 'placeholder' => null, 'required' => 0],
            ['form_id' => 4, 'name' => 'creating_high_performing_environment_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Creating a high-performing work environment"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 5, 'name' => 'provide_clear_purpose', 'element' => 'radio', 'label' => 'Provide clear purpose, vision and deliverables', 'hint' => 'I provide a clear sense of purpose, direction and realistic operational deliverables, anticipating future trends and challenges, ensuring everyone understands how their role contributes to team and departmental objectives, broader organisational goals, and the future of the NHS, including the 10-year plan.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 5, 'name' => 'manage_performance', 'element' => 'radio', 'label' => 'Manage and measure performance', 'hint' => 'I manage and measure the performance of colleagues within my areas of responsibility, ensuring provision of constructive feedback, celebrating achievements, and addressing underperformance in a timely and compassionate manner.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 5, 'name' => 'manage_conflict', 'element' => 'radio', 'label' => 'Manage conflict and sensitive conversations', 'hint' => 'I approach challenging and sensitive conversations with professionalism and composure, actively listening to all parties and identifying mechanisms, including expert support and advice to de-escalate potential or actual conflict.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 5, 'name' => 'managing_performance_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Managing performance"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 6, 'name' => 'allocate_and_optimise_resources', 'element' => 'radio', 'label' => 'Allocate and optimise resources', 'hint' => 'I understand the importance of optimising resources for current and future needs, working collaboratively to identify opportunities for improvement and digitalisation, and maximise effectiveness and efficiency.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 6, 'name' => 'manage_public_money_effectively', 'element' => 'radio', 'label' => 'Manage public money effectively', 'hint' => 'I recognise that I work in a publicly funded organisation and ensure that my actions future-proof the NHS, by seeking ways to deliver financial accountability, reduce waste, optimise efficiency, sustainability, value for money, and responsible spending.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 6, 'name' => 'use_data_evidence_and_critical_thinking', 'element' => 'radio', 'label' => 'Use data, evidence and critical thinking', 'hint' => 'I use appropriate digital tools to interrogate data and evidence, including subject matter experts, applying findings to identify opportunities which future-proof the service, and enable my areas of responsibility to be more innovative, efficient, productive, and sustainable.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 6, 'name' => 'maximising_resources_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Maximising resources and efficiencies"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 7, 'name' => 'respond_to_patient_safety', 'element' => 'radio', 'label' => 'Respond to patient safety, needs and preferences', 'hint' => 'I understand patient uniqueness and diversity, prioritising safety by reporting concerns and incidents, and adapting my approach to individual needs and preferences.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 7, 'name' => 'prioritise_people_centred_care', 'element' => 'radio', 'label' => 'Prioritise people-centred care to deliver a quality service', 'hint' => 'I proactively support the reduction of health inequalities and improve patient outcomes by recognising and valuing diversity, building trust, and promoting inclusion to provide care that centres on each person\'s individual needs.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 7, 'name' => 'apply_compliance', 'element' => 'radio', 'label' => 'Apply compliance, governance and policy to improve patient outcomes', 'hint' => 'I understand and identify the policies and procedures relevant to my areas of responsibility, applying these to ensure best practice and continuously improve patient outcomes.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 7, 'name' => 'improving_patient_outcomes_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Improving patient outcomes and experiences"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 8, 'name' => 'drive_continuous_improvement', 'element' => 'radio', 'label' => 'Drive continuous improvement and innovation', 'hint' => 'I seek ways to test new ideas, improve processes, and implement continuous improvement solutions, to drive positive change and solve problems within my areas of responsibility.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 8, 'name' => 'transform_through_technology', 'element' => 'radio', 'label' => 'Transform through technology and innovation', 'hint' => 'I use technology and innovation to enhance my areas of responsibility\'s effectiveness and improve patient outcomes, assessing the positive and negative impact of these changes to minimise risk.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 8, 'name' => 'support_others_through_change', 'element' => 'radio', 'label' => 'Support others through change', 'hint' => 'I embrace and support change, demonstrating followership through positive communication, and by signposting help and advice for others, where necessary.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 8, 'name' => 'Leading_with_a_mindset_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Leading with a mindset of improvement and innovation"', 'placeholder' => null, 'required' => 0],

            ['form_id' => 9, 'name' => 'build_impactful_relationships', 'element' => 'radio', 'label' => 'Build impactful relationships', 'hint' => 'I build positive working relationships with colleagues, patients, citizens and other stakeholders, treating everyone with respect and valuing their input and perspective.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 9, 'name' => 'lead_a_collaborative_team', 'element' => 'radio', 'label' => 'Lead a collaborative team', 'hint' => 'I promote collaborative working within my areas of responsibility, actively contributing to cross-team initiatives and ensuring everyone\'s input is heard and valued, to build inclusive, innovative and high-performing working environments and relationships.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 9, 'name' => 'actively_share_good_practice', 'element' => 'radio', 'label' => 'Actively share good practice', 'hint' => 'I model the sharing of good practice and learning, proactively seeking information and knowledge from others to enhance my understanding and professional development.', 'placeholder' => null, 'required' => 0],
            ['form_id' => 9, 'name' => 'working_collaboratively_notes', 'element' => 'textarea', 'label' => 'Additional notes', 'hint' => 'Additional notes or comments regarding "Working collaboratively to achieve results"', 'placeholder' => null, 'required' => 0],
        ]);
    }
}
